[package]
name = "cell"
version = "0.1.0"
authors = ["charles <charles.mcallister@dunnker.com>"]
license-file = "license.txt"

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
pistoncore-input = "*"
rand = "*"